###############################################################################################################################
#   ビルドトリガー (branch)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml
###############################################################################################################################
trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - revert-*
  paths:
    exclude:
      - '**/*.md'
      - .github/workflows/*.yml
      - .gitignore
      - .travis.yml
      - appveyor.yml

###############################################################################################################################
#   ビルドトリガー (Pull Request)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation
###############################################################################################################################
pr:
  branches:
    include:
      - master
      - develop
      - feature/*
      - revert-*
  paths:
    exclude:
      - '**/*.md'
      - .gitignore
      - .travis.yml
      - appveyor.yml

###############################################################################################################################
#   jobs/job 定義
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
###############################################################################################################################
jobs:

# サクラエディタのビルドを行う JOB (VS2017)
# * サクラエディタ本体
# * HTML Help
# * Installer
# * 単体テスト
- template: ci/azure-pipelines/template.job.build-unittest.yml
  parameters:
    name: VS2017
    vmImage: 'VS2017-Win2016'
    displayName: VS2017
    ARG_VSVERSION: 15

# サクラエディタのビルドを行う JOB (VS2019)
# * サクラエディタ本体
# * HTML Help
# * Installer
# * 単体テスト
# https://devblogs.microsoft.com/devops/hosted-pipelines-announcements-vs-2019-mojave-and-more/
#
- template: ci/azure-pipelines/template.job.build-unittest.yml
  parameters:
    name: VS2019
    vmImage: 'windows-2019'
    displayName: VS2019
    ARG_VSVERSION: 16

# サクラエディタのビルドを行う JOB(MinGW)
# * サクラエディタ本体
# * 単体テスト
- template: ci/azure-pipelines/template.job.build-on-msys2.yml
  parameters:
    name: MinGW
    vmImage: 'VS2017-Win2016'
    displayName: MinGW

# SonarQube で解析を行う JOB
- template: ci/azure-pipelines/template.job.SonarQube.yml
  parameters:
    name: SonarQube
    vmImage: 'VS2017-Win2016'
    displayName: SonarQube

# Cppcheck を行う JOB
- template: ci/azure-pipelines/template.job.cppcheck.yml
  parameters:
    name: cppcheck
    vmImage: 'VS2017-Win2016'
    displayName: cppcheck

# doxygen を行う JOB
- template: ci/azure-pipelines/template.job.doxygen.yml
  parameters:
    name: doxygen
    vmImage: 'VS2017-Win2016'
    displayName: doxygen

# 文字コードのチェックを行う JOB
- template: ci/azure-pipelines/template.job.checkEncoding.yml
  parameters:
    name: checkEncoding
    vmImage: 'VS2017-Win2016'

#############################################################################################################
#   Python スクリプトのコンパイル確認を行う job
#############################################################################################################
- template: ci/azure-pipelines/template.job.python-check.yml
  parameters:
    name: script_check
    vmImage: 'VS2017-Win2016'
    displayName: script_check
