###############################################################################################################################
#   ビルドトリガー (branch)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&viewFallbackFrom=vsts&tabs=yaml
###############################################################################################################################
trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    exclude:
      - "*.md"
      - .travis.yml
      - appveyor.yml

###############################################################################################################################
#   ビルドトリガー (Pull Request)
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation
###############################################################################################################################
pr:
  branches:
    include:
      - master
      - develop
      - feature/*

###############################################################################################################################
#   jobs/job 定義
#
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
###############################################################################################################################
jobs:

# サクラエディタのビルドを行う JOB
# * サクラエディタ本体
# * HTML Help
# * Installer
# * 単体テスト
- template: ci/azure-pipelines/template.job.build-unittest.yml
  parameters:
    name: VS2017
    vmImage: 'VS2017-Win2016'
    displayName: VS2017

# SonarQube を行う JOB
- template: ci/azure-pipelines/template.job.SonarQube.yml
  parameters:
    name: SonarQube
    vmImage: 'VS2017-Win2016'
    displayName: SonarQube

# Cppcheck を行う JOB
- template: ci/azure-pipelines/template.job.cppcheck.yml
  parameters:
    name: cppcheck
    vmImage: 'VS2017-Win2016'
    displayName: cppcheck

# doxygen を行う JOB
- template: ci/azure-pipelines/template.job.doxygen.yml
  parameters:
    name: doxygen
    vmImage: 'VS2017-Win2016'
    displayName: doxygen

# 文字コードのチェックを行う JOB
- template: ci/azure-pipelines/template.job.checkEncoding.yml
  parameters:
    name: checkEncoding
    vmImage: 'VS2017-Win2016'

#############################################################################################################
#   Python スクリプトのコンパイル確認を行う job
#############################################################################################################
- template: ci/azure-pipelines/template.job.python-check.yml
  parameters:
    name: script_check
    vmImage: 'VS2017-Win2016'
    displayName: script_check
