#############################################################################################################
#   必要な mingw-w64-gcc をインストール手順の 'steps' を定義するテンプレート
#
#   parameters
#       なし
#############################################################################################################
steps:
  - script: C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm p7zip"
    displayName: install 7zip

  - script: C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"
    displayName: install MinGW-w64-gtest
