#############################################################################################################
#	必要な Python module をインストール手順の 'steps' を定義するテンプレート
#
#	parameters
#		なし
#############################################################################################################
steps:
- script: pip install openpyxl --user
  displayName: install openpyxl --user
