name: MinGW Build and Test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      BuildPlatform: MinGW
      Configuration: ${{ matrix.configuration }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            libiconv
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-7zip

      - name: Check iconv
        shell: msys2 {0}
        continue-on-error: true
        run: |
          which iconv

      - shell: msys2 {0}
        run: |
          pacman -U --noconfirm https://mirror.msys2.org/msys/x86_64/libiconv-1.18-1-x86_64.pkg.tar.zst

      - name: Check iconv
        shell: msys2 {0}
        run: |
          which iconv

      - name: Show environment variables for debug
        run: set
        shell: cmd

      - name: Build with MinGW-w64-gcc
        shell: msys2 {0}
        run: ./build-gnu.bat ${{ env.BuildPlatform }} ${{ env.Configuration }} --no-test

      - name: Run unit tests
        shell: cmd
        run: tests1.exe --gtest_output=xml:${{ github.workspace }}/tests1.exe-googletest-${{ env.BuildPlatform }}-${{ env.Configuration }}.xml
        working-directory: ${{ github.workspace }}/${{ env.BuildPlatform }}/${{ env.Configuration }}
