name: Cppcheck

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: windows-latest
    strategy:
      matrix:
        BuildPlatform: [Win32, x64]
        Configuration: [Release]
    env:
      BuildPlatform: ${{ matrix.BuildPlatform }}
      Configuration: ${{ matrix.Configuration }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-cppcheck

      - name: Show environment variables for debug
        run: set
        shell: cmd

      - name: Run cppcheck
        run: ./run-cppcheck.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}
        shell: msys2 {0}

      - name: Zip files for artifacts
        run: zipArtifacts.bat ${{ env.BuildPlatform }} ${{ env.Configuration }}
        shell: cmd

      - name: Upload cppcheck log artifact
        uses: actions/upload-artifact@v6
        with:
          name: cppcheck_${{ env.BuildPlatform }}_${{ env.Configuration }}
          path: '**Log.zip'
